version: 2

models:
  - name: dim_channels
    description: "Telegram channel dimension table with channel metadata"
    columns:
      - name: channel_key
        description: "Surrogate primary key for channel"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Original Telegram channel name"
        tests:
          - not_null
      - name: channel_type
        description: "Channel category (Pharmaceutical, Cosmetics, Medical)"
        tests:
          - accepted_values:
              values: ['Pharmaceutical', 'Cosmetics', 'Medical']
      - name: total_posts
        description: "Total number of posts from this channel"
        tests:
          - not_null
      - name: avg_views
        description: "Average views per post"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_key
        description: "Surrogate primary key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date timestamp"
        tests:
          - not_null
      - name: year
        description: "Year component"
        tests:
          - not_null

  - name: fct_messages
    description: "Fact table for Telegram messages with metrics"
    columns:
      - name: message_id
        description: "Original Telegram message ID"
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
          - not_negative:
              config:
                where: "view_count < 0"
      - name: forward_count
        description: "Number of times message was forwarded"
        tests:
          - not_negative:
              config:
                where: "forward_count < 0"
      - name: message_length
        description: "Length of message text in characters"
        tests:
          - not_negative:
              config:
                where: "message_length < 0"

  - name: fct_image_detections
    description: "Fact table for YOLO image detection results"
    columns:
      - name: message_id
        description: "Foreign key to fct_messages"
        tests:
          - not_null
          - relationships:
              to: ref('fct_messages')
              field: message_id
      - name: confidence_score
        description: "YOLO detection confidence score"
        tests:
          - accepted_values:
              values: ['>= 0', '<= 1']